version: "3.8"

services:
  postgresql-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - devnet
  
  seq:
    container_name: seq_log
    image: datalust/seq:latest
    ports:
      - 8082:80
      - 5341:5341
    environment:      
      - ACCEPT_EULA=Y 

volumes:
  db:
    driver: local
      
networks:
  devnet:
    driver: bridge
    name: devnet_network
